### ISSUE TITLE
Contractor swipes LEFT on project (PATCH 'api/v1/contractors/:id/projects/:id')

### ISSUE THREAD

**Issue by james-cape** [james-cape/fixup_backend#21]
- [x] Documented in README
- [x] Saved in Postman

As a logged-in Contractor,
When I visit ‘/contractors/:id/projects’,
I see a project.
The contractor_project was created in the database when the project was sent and defaults with false for contractor_choice, user_choice?, and completed?.
And when I swipe left on the project,
It updates the contractor_choice to "1",
And I see another project appear.

```
PATCH 'api/v1/contractors/:id/projects/:id'

request: {
  updated_contractor_choice: 1
}

response: {
  message: 'successful'
}
```

**Comment by tnodland** [comment]
Closing issue, we have taken a different route to solve this problem, see #35
